spring.application.name=ms-productos

# ===============================
# MYSQL
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/pedidos360_productos
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# SERVIDOR
# ===============================

server.port=8081

# ===============================
# AZURE ENTRA ID
# ===============================

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/0844a9ad-f458-47d0-8036-0f2080309ddc/v2.0