spring.application.name=ms-productos

spring.datasource.url=jdbc:mysql://localhost:3306/pedidos360_productos
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081